---
- name: add apt repository
  apt_repository:
    repo: "{{ nginx_apt_repo }}"
    state: present


- name: add src repository
  apt_repository:
    repo: "{{ nginx_apt_src_repo }}"
    state: present


- name: add apt key
  apt_key:
    keyserver: "{{ nginx_keyserver_url }}"
    id: "{{ nginx_repo_key_id }}"


- name: install nginx
  apt:
    name: nginx
    update_cache: yes


- name: stop service
  service:
    name: nginx
    state: stopped


- name: create config
  template:
    src: "default.j2"
    dest: "{{ nginx_cfg_dest }}"


- name: generate self-signed certificate
  command: openssl req \
    -x509 \
    -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -subj '/C=aa/ST=bb/L=cc/O=dd/CN={{ base_domain }}'
    -keyout "{{ nginx_home }}/{{ nginx_tls_key }}" \
    -out "{{ nginx_home }}/{{ nginx_tls_crt }}"

- name: start and enable service
  service:
    name: nginx
    state: started
    enabled: yes
