nexus_home: /opt/data/nexus
nexus_user: nexus
nexus_group: nexus
nexus_docker_compose_dest: "{{ nexus_home }}/docker-compose.yaml"
nexus_login_user: admin
nexus_login_pass: admin123
nexus_port: 9091
nexus_cfg_files:
  - create_jenkins_user
  - create_main_jenkins_ci_user
  - create_jenkins_plugins_raw_repo
  - create_main_docker_repo
  - create_models_raw_repo
  - create_pypi_hosted_repo
